name: run-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pest:
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        laravel: ['9.*', '10.*', '11.*', '12.*']
        php: [8.1, 8.2, 8.3]
        stability: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 11.*
            php: 8.1
          - laravel: 12.*
            php: 8.1
        include:
          - laravel: 9.*
            testbench: 7.*
            phpunit: 9.*
          - laravel: 10.*
            testbench: 8.*
            phpunit: 10.*
            carbon: ^2.63
          - laravel: 11.*
            testbench: 9.*
            phpunit: 11.*
            carbon: ^2.63
          - laravel: 12.*
            testbench: 10.*
            phpunit: '8.2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
